
version: '4.10'
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local